<?php
/**
 * Default Subject Lists by Class Level
 * Schools can use these as templates and customize as needed
 */

return [
    // Primary Classes
    'Primary 1' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'Primary 2' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'Primary 3' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'Primary 4' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'Primary 5' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'Primary 6' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    // Junior Secondary Classes
    'JSS 1' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Business Studies', 'is_core' => true],
        ['name' => 'Home Economics', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],
    'JSS1' => [ // Alias without space
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Business Studies', 'is_core' => true],
        ['name' => 'Home Economics', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'JSS 2' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Business Studies', 'is_core' => true],
        ['name' => 'Home Economics', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],
    'JSS2' => [ // Alias without space
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Business Studies', 'is_core' => true],
        ['name' => 'Home Economics', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'JSS 3' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Business Studies', 'is_core' => true],
        ['name' => 'Home Economics', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],
    'JSS3' => [ // Alias without space
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Basic Science', 'is_core' => true],
        ['name' => 'Basic Technology', 'is_core' => true],
        ['name' => 'Social Studies', 'is_core' => true],
        ['name' => 'Cultural & Creative Arts', 'is_core' => true],
        ['name' => 'Physical & Health Education', 'is_core' => true],
        ['name' => 'Business Studies', 'is_core' => true],
        ['name' => 'Home Economics', 'is_core' => true],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    // Senior Secondary Classes - Science Track
    'SSS 1' => [
        // Core subjects for all SSS 1
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        // Science electives
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        // Arts/Commercial electives
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],
    'SSS1' => [ // Alias without space
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'SSS 2' => [
        // Core subjects for all SSS 2
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        // Science electives
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        // Arts/Commercial electives
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],
    'SSS2' => [ // Alias without space
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'SSS 3' => [
        // Core subjects for all SSS 3
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        // Science electives
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        // Arts/Commercial electives
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],
    'SSS3' => [ // Alias without space
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    // SS aliases (some schools use SS instead of SSS)
    'SS 1' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],
    'SS1' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'SS 2' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],
    'SS2' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],

    'SS 3' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],
    'SS3' => [
        ['name' => 'Mathematics', 'is_core' => true],
        ['name' => 'English Language', 'is_core' => true],
        ['name' => 'Civic Education', 'is_core' => true],
        ['name' => 'Physics', 'is_core' => false],
        ['name' => 'Chemistry', 'is_core' => false],
        ['name' => 'Biology', 'is_core' => false],
        ['name' => 'Literature in English', 'is_core' => false],
        ['name' => 'Government', 'is_core' => false],
        ['name' => 'Economics', 'is_core' => false],
        ['name' => 'Commerce', 'is_core' => false],
        ['name' => 'Accounting', 'is_core' => false],
        ['name' => 'Christian Religious Studies', 'is_core' => false],
        ['name' => 'Islamic Religious Studies', 'is_core' => false],
        ['name' => 'Geography', 'is_core' => false],
        ['name' => 'Agricultural Science', 'is_core' => false],
        ['name' => 'Further Mathematics', 'is_core' => false],
        ['name' => 'Technical Drawing', 'is_core' => false],
        ['name' => 'French', 'is_core' => false],
        ['name' => 'Computer Studies', 'is_core' => false],
    ],
];
